"use client";
import { useState } from "react";
import Image from "next/image";
import { ArrowDownToLine, ArrowLeft, Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlus, Combine, FileText, Gamepad2, Gift, Layers3, Menu, MessageCircle, MoveUp, Pause, Play, Quote, RotateCcw, Route, Shrink, Target, UserRound, X } from "lucide-react";
const faq = [
  ["לאיזה גיל הקורס מתאים?", "הקורס מתאים ל־[טווח הכיתות הסופי], בהתאם לרמת החשבון של הילד ולא רק לגיל."],
  ["האם הילד צריך ידע קודם?", "לא מעבר לבסיס שמתאים לשלב שלו. הקורס בנוי כך שכל מפתח נלמד בצורה ברורה ובהדרגה."],
  ["האם צריך לשבת עם הילד בזמן הקורס?", "תלוי בגיל וביכולת שלו לעבוד עצמאית. ילדים מסוימים יוכלו להתקדם לבד, ואחרים ירוויחו מליווי קצר של הורה בתחילת הדרך."],
  ["כמה זמן כל שיעור?", "כ־[X] דקות. השיעורים קצרים וממוקדים כדי לא להעמיס ולשמור על ריכוז."],
  ["כמה פעמים בשבוע מומלץ ללמוד?", "מומלץ להתקדם בקצב קבוע של [X פעמים בשבוע], עם זמן לתרגול בין שיעור לשיעור."],
  ["מה עושים אם הילד עדיין סופר על האצבעות?", "זה בדיוק אחד הדברים שהקורס נועד לעזור בהם. הילדים לומדים דרכי חישוב שמאפשרות להם בהדרגה להישען פחות על ספירה ויותר על הבנה של המספרים והתרגיל."],
  ["מה ההבדל בין הקורס לבין עוד דפי תרגול?", "בקורס לא רק מתרגלים תרגילים. הילדים לומדים איך לגשת לסוגים שונים של תרגילים בעזרת מפתחות חישוב ברורים, ואז מתרגלים את השימוש בהם."],
  ["מה קורה אם הילד נתקע או יש לנו שאלה?", "אפשר לפנות בקבוצת ה־WhatsApp עם יפתח, לשאול, להתייעץ ולקבל הכוונה לאורך הדרך."],
  ["לכמה זמן יש גישה לקורס?", "הגישה פתוחה למשך [X חודשים], כך שאפשר להתקדם בקצב שמתאים לכם ולחזור לשיעורים ולתרגולים לפי הצורך."],
  ["אפשר לצפות מכל מכשיר?", "כן, הקורס זמין דרך [מחשב / טאבלט / טלפון — לפי מה שיהיה בפועל]."],
  ["מה מדיניות הביטול?", "[להשלים לפי המדיניות שתיקבע.]"],
];
const keys = [
  { title: "פירוק", text: "נלמד לזהות מיד איך מספרים מתפרקים לחלקים, בלי לספור באצבעות.", icon: Layers3 },
  { title: "טיפוס", text: "נפתח ניחוש מספרי ונלמד לטפס מהמספר הגדול בלי להתחיל מאפס.", icon: MoveUp },
  { title: "קפיצה ל־10", text: "נלמד לזהות מיד כמה חסר לעשר, בלי לספור כל קומה.", icon: Target },
  { title: "הדבקה", text: "נלמד לחבר יחידות לעשר ולזהות מיד את המספר שנוצר.", icon: Combine },
  { title: "גלישה קטנה", text: "נלמד לגלוש ממספר דו־ספרתי ישר לעשר באמצעות הורדת האחדות.", icon: ArrowDownToLine },
  { title: "עצירה ב־10", text: "נלמד לפרק חיבור, לעצור בעשר ולהמשיך בלי ספירה ממושכת.", icon: Pause },
  { title: "היפוך קטן", text: "נלמד להפוך חיסור לשאלת חיבור ולמצוא את החסר בלי לספור לאחור.", icon: RotateCcw },
  { title: "היפוך גדול", text: "נלמד להפוך חיסור לחיבור ולחשב בקפיצות דרך עשר.", icon: Route },
  { title: "הקטנה", text: "נלמד להקטין תרגיל ליחידות ולהחזיר את העשרות לתשובה.", icon: Shrink },
  { title: "גלישה גדולה", text: "נלמד לגלוש לעשר ולבצע תיקון קטן בדרך לתשובה.", icon: CirclePlus },
];
const testimonials = [
  {
    quote: "הי יפתח, החדשות המעולות הן שיובל סיים עם בגרות של 86. אחרי שהוציא 99 במתכונת והוגש על 92 (אחרי שהתעקשת שנתעקש עם ביה״ס). תודה ענקית על מה שעשית בשבילנו. יובל לא רק הצליח במבחן, הוא גם גילה שהוא ממש לא רע במתמטיקה, ואפילו טוב. תגלית של ממש! תודה ענקית על הגישה המעשית שלך ללימוד, על ההיכרות המעמיקה עם המבחנים, על האופן שכדאי ׳לתקוף׳ אותם ובעיקר על הדרך החיובית שיש לך להסתכל על אתגרים בכלל ובמתמטיקה בפרט. השלמתם חומר של שנה, במבצע בזק של 10 מפגשים. הוא קיבל תיאבון ושוקל לגשת למועד הבא כדי להשיג ציון עוד יותר טוב (אז אולי עוד נתראה למרתון אחד). יחסרו לי השיחות הקצרצרות שלנו על הורות בין לבין, שוב תודה.",
    author: "קובי, אבא של יובל",
    sample: false,
  },
  {
    quote: "כבר אחרי כמה שיעורים ראינו שינוי בדרך שבה נועה ניגשת לתרגילים. במקום להיבהל היא עוצרת, מפרקת את המספרים ומנסה דרך שמתאימה לה. היא אפילו התחילה להסביר לנו איך היא חושבת.",
    author: "אמא של נועה, כיתה ב׳",
    sample: true,
  },
  {
    quote: "התרגול הקצר והמשחקים התאימו בדיוק לעידו. הוא הפסיק לנחש והתחיל לחשב בביטחון, וגם כשיש טעות הוא יודע לחזור ולבדוק מה קרה בדרך.",
    author: "אבא של עידו, כיתה ג׳",
    sample: true,
  },
];
function Cta({light=false}:{light?:boolean}){return <a className={`cta ${light?"light":""}`} href="#join">להצטרפות לקורס <ArrowLeft size={21}/></a>}
function Brand(){return <a className="brand" href="#top" aria-label="kidodo — מפתחות לידע — לראש העמוד"><Image className="brand-logo" src="/kidodo-wordmark.png" alt="kidodo" width={1840} height={1024}/><span className="brand-tagline">מפתחות לידע</span></a>}
export default function Home(){const [open,setOpen]=useState(false);const [testimonialIndex,setTestimonialIndex]=useState(0);const testimonial=testimonials[testimonialIndex];const moveTestimonial=(direction:number)=>setTestimonialIndex((testimonialIndex+direction+testimonials.length)%testimonials.length);return <div dir="rtl" id="top"><header className="header"><Brand/><button className="menu-toggle" aria-label={open?"סגירת תפריט":"פתיחת תפריט"} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"nav open":"nav"} aria-label="ניווט ראשי"><a href="#difference" onClick={()=>setOpen(false)}>איך זה עובד?</a><a href="#audience" onClick={()=>setOpen(false)}>למי זה מתאים?</a><a href="#faq" onClick={()=>setOpen(false)}>שאלות נפוצות</a><div className="nav-actions"><a className="nav-login" href="/login" onClick={()=>setOpen(false)}><UserRound size={17}/>כניסת משתמש</a><a className="nav-join" href="#join" onClick={()=>setOpen(false)}>להצטרפות לקורס</a></div></nav></header><main>
<section className="hero panel"><div className="hero-content"><h1 className="dot-heading">לומדים לחשוב אחרת</h1><p>קורס חשבון שמעניק לילדים את מפתחות הידע — טכניקות ורעיונות שבונים בצורה נכונה את הגישה למספרים.</p><Cta/></div><div className="hero-visual"><Image className="hero-photo" src="/keydodo-hero-v3.webp" alt="ילד לומד חשבון בעזרת הקורס, לצד צעצוע דודו שמחזיק מפתח זהב" width={1536} height={1024} priority sizes="(min-width: 700px) 50vw, 100vw"/></div><ChevronDown className="scroll-indicator"/></section>
<section className="story panel" id="story"><div className="story-inner"><h2 className="dot-heading">אז מה בעצם אנחנו מלמדים אחרת?</h2><p>יפתח מסביר איך נולדה השיטה, למה ילדים נתקעים בחישוב ואיך מפתחות החישוב עוזרים להם לגשת לתרגילים בדרך פשוטה יותר.</p><div className="story-video" role="img" aria-label="מקום שמור לסרטון של יפתח"><span className="play-button" aria-hidden="true"><Play fill="currentColor" size={28}/></span></div></div></section>
<section className="familiar panel"><h2 className="dot-heading">זה מוכר לכם?</h2><div className="bubbles"><div>סופרים על האצבעות גם כשהמספרים כבר גדולים</div><div>בחיסור הולכים לאיבוד בספירה לאחור</div><div>תרגיל שנראה קצת אחרת מרגיש פתאום כמו משהו חדש</div><div>כל חישוב דורש הרבה ריכוז ומאמץ</div></div><p className="familiar-end">לפעמים הקושי הוא לא בחשבון עצמו, אלא בדרך שבה ניגשים לתרגיל.</p><ChevronDown className="section-chevron"/></section>
<section className="different-way panel" id="difference"><div className="different-way-inner"><h2>מה שונה<br/>בדרך שלנו?</h2><div className="difference-card"><p className="difference-lead">אנחנו לא מלמדים רק איך לפתור תרגיל.</p><p className="difference-emphasis">אנחנו מלמדים איך לגשת אליו — לפרק מספרים, לזהות דפוסים ולבחור דרך חישוב יעילה.</p></div><Cta/></div></section>
<section className="method panel"><h2>10 מפתחות<br/>החישוב</h2><div className="method-intro"><p>מפתחות החישוב הם טכניקות פשוטות שעוזרות לילדים לדעת מה לעשות כשהם פוגשים תרגיל.</p><p>כל מפתח נשען על הקודמים לו, וביחד הם בונים דרך חשיבה ברורה וגמישה.</p></div><div className="key-grid">{keys.map(({title,text,icon:KeyIcon},i)=><article className="key-card" key={title}><div className="key-card-top"><span className="key-number">{i+1}</span><span className="key-icon" aria-hidden="true"><KeyIcon size={29} strokeWidth={2.1}/></span></div><h3>{title}</h3><p>{text}</p></article>)}</div><ChevronDown className="section-chevron"/></section>
<section className="learning panel" id="learning"><div className="learning-inner"><h2>איך לומדים<br/>בקורס?</h2><div className="learning-intro"><p>בכל שיעור הילדים לומדים מפתח חישוב אחד, רואים איך הוא עובד ומתרגלים אותו.</p><p>כך, שלב אחרי שלב, הם בונים ארגז כלים שאפשר להשתמש בו גם בתרגילים חדשים.</p></div><h3>איך הלמידה בנויה?</h3><div className="learning-steps"><article><span>1</span><p><strong>10 שיעורים קצרים</strong> — כל שיעור מתמקד במפתח אחד.</p></article><article><span>2</span><p><strong>10–15 דקות לשיעור</strong> — כדי לשמור על ריכוז.</p></article><article><span>3</span><p><strong>למידה בקצב אישי</strong> — אפשר לעצור, לחזור ולתרגל שוב.</p></article></div></div><div className="learning-extra"><div className="learning-extra-inner"><h3>ומה מקבלים<br/>מעבר לשיעורים?</h3><div className="extras"><article><span className="extra-icon"><Gamepad2 size={34}/></span><p><strong>משחקים אינטראקטיביים לתרגול</strong> — מיישמים את המפתחות תוך כדי משחק.</p></article><article><span className="extra-icon"><FileText size={34}/></span><p><strong>דפי עבודה להדפסה</strong> — לתרגול נוסף מחוץ למסך.</p></article><article><span className="extra-icon whatsapp"><MessageCircle size={34}/></span><p><strong>קבוצת WhatsApp עם יפתח</strong> — מקום לשאול, להתייעץ ולקבל הכוונה כשצריך.</p></article></div><p className="learning-access">גישה מכל מכשיר <span>|</span> גישה ל־[X] חודשים <span>|</span> אפשר ללמוד בקצב שלכם</p></div></div></section>
<section className="audience panel" id="audience"><div className="audience-top"><h2>למי הקורס<br/>מתאים?</h2><h3>מתאים במיוחד ל:</h3><div className="grade-cards"><article><span><UserRound size={40}/></span><p>תלמידי כיתה א׳ מתקדמים</p></article><article><span><UserRound size={40}/></span><p>תלמידי כיתה ב׳</p></article><article><span><UserRound size={40}/></span><p>תלמידי כיתה ג׳ שעדיין מתקשים במיומנויות החישוב הבסיסיות</p></article></div></div><div className="audience-wave" aria-hidden="true"/><div className="audience-bottom"><h3>וגם לילדים ש:</h3><ul><li><span><Check size={22}/></span><p>עדיין סופרים על האצבעות או מתקשים לעבור לחישוב בעל פה</p></li><li><span><Check size={22}/></span><p>מתבלבלים בחיסור או מאבדים את הדרך באמצע</p></li><li><span><Check size={22}/></span><p>נתקעים כשהתרגיל נראה קצת אחרת</p></li><li><span><Check size={22}/></span><p>משקיעים הרבה מאמץ בחישובים פשוטים יחסית</p></li></ul><p className="audience-goal">המטרה היא לבנות דרך חישוב ברורה שהילד יוכל לחזור אליה שוב ושוב.</p><small className="approval-note">חלוקת הכיתות ממתינה לאישור יפתח.</small></div></section>
<section className="founder" id="founder"><div className="founder-photo"><Image src="/yiftach-section-reference.png" alt="יפתח, מפתח שיטת מפתחות החישוב" width={264} height={765}/></div><div className="founder-copy"><h2>נעים להכיר,<br/>אני יפתח</h2><p>את השיטה פיתחתי מתוך עבודה עם ילדים ומתוך שאלה שחזרה שוב ושוב:</p><p className="founder-question">למה ילד שמבין, עדיין נתקע בתרגיל?</p><p>ראיתי שלפעמים הם לא צריכים עוד הסבר — אלא דרך אחרת לגשת לתרגיל. מכאן נולדו מפתחות החישוב: טכניקות פשוטות שעוזרות לפרק, לזהות ולבחור דרך חישוב יעילה.</p><p>אני עובד כבר <strong>[X שנים]</strong> עם ילדים בגילאי בית ספר יסודי, ולימדתי <strong>[מאות תלמידים / במסגרות שונות]</strong>.</p><p className="founder-closing">הכי חשוב לי שהילד יסתכל על תרגיל וירגיש: אני יודע איך לגשת לזה.</p><span className="founder-signature" aria-hidden="true">יפתח</span></div></section>
<section className="testimonials panel" id="testimonials"><div className="testimonials-inner"><h2>מה הורים<br/>מספרים?</h2><p className="testimonials-intro">הדרך הכי טובה להבין מה משתנה היא לשמוע מהורים שכבר ראו את זה קורה בבית.</p><div className="testimonial-stage"><article className="testimonial-card" aria-live="polite"><Quote className="quote-mark" size={42} fill="currentColor" aria-hidden="true"/><p>{testimonial.quote}</p><strong>{testimonial.author}</strong>{testimonial.sample&&<small>עדות לדוגמה</small>}</article><button type="button" className="testimonial-arrow prev" aria-label="המלצה קודמת" onClick={()=>moveTestimonial(-1)}><ChevronRight/></button><button type="button" className="testimonial-arrow next" aria-label="המלצה הבאה" onClick={()=>moveTestimonial(1)}><ChevronLeft/></button></div><div className="testimonial-dots" aria-label="מיקום בקרוסלת ההמלצות">{testimonials.map((item,index)=><button key={item.author} type="button" className={index===testimonialIndex?"active":""} aria-label={`מעבר להמלצה ${index+1}`} aria-current={index===testimonialIndex?"true":undefined} onClick={()=>setTestimonialIndex(index)}/>)}</div></div></section>
<section className="offer panel" id="join"><div className="offer-inner"><h2>מצטרפים ולומדים<br/>לחשוב אחרת</h2><p className="offer-intro">קורס דיגיטלי שמלמד ילדים את מפתחות החישוב — עם שיעורים קצרים, משחקים אינטראקטיביים ותרגול מובנה.</p><div className="course-box" aria-label="קורס אונליין של kidodo"><span className="course-box-brand"><Image src="/kidodo-wordmark.png" alt="kidodo" width={1840} height={1024}/></span><strong>קורס אונליין</strong><Image src="/kidodo-mascot.webp" alt="דמות kidodo" width={95} height={95}/></div><div className="offer-list"><h3>מה מקבלים בקורס?</h3><ul><li><span><Check size={21}/></span>גישה לכל שיעורי הקורס</li><li><span><Check size={21}/></span>משחקים אינטראקטיביים לתרגול</li><li><span><Check size={21}/></span>תרגול מובנה לאורך הקורס</li><li><span><Check size={21}/></span>גישה ל־[X חודשים]</li></ul></div><div className="offer-bonuses"><h3>ובנוסף</h3><article><span><Gift size={24}/></span><p><strong>בונוס: דפי עבודה להדפסה</strong> — לתרגול נוסף גם מחוץ למסך.</p></article><article><span><Gift size={24}/></span><p><strong>בונוס: מנוי לתמיד לאפליקציית מתיקה</strong> — סרטונים, משחקים, תרגולים ועוד.</p></article></div><div className="price-card"><p className="price-label">מחיר</p><p className="price">[מחיר מלא] <span>|</span> [מחיר השקה, אם יש]</p>{/* TODO(Base44): Connect this button to the hosted payment page when it is ready. */}<button className="payment-button" type="button">מעבר לתשלום <ArrowLeft size={21}/></button><p className="purchase-notes">[אפשרות לתשלומים] <span>|</span> [מדיניות ביטול / אחריות]</p></div></div></section>
<section className="about panel"><h2 className="dot-heading">נעים להכיר,<br/>kidodo</h2><p>kidodo נולדה מתוך אמונה שילדים יכולים הרבה יותר – כשנותנים להם ללמוד בדרך שמתאימה להם.</p><p>אנחנו מפתחים קורסים דיגיטליים בחשבון ובהמשך גם בשפה, שמכניסים סקרנות, ביטחון והנאה מהלמידה.</p><div className="about-mascot"><Image src="/kidodo-mascot.webp" alt="הדודו של kidodo" width={255} height={255}/><span>לומד<br/>חושב<br/>גדל</span></div></section>
<section className="faq panel" id="faq"><h2>שאלות<br/>נפוצות</h2><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span className="faq-toggle" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><section className="final-cta panel"><div className="final-mascot"><Image src="/kidodo-mascot.webp" alt="דמות kidodo מזמינה להתחיל" width={230} height={230}/></div><h2>מוכנים להתחיל<br/>לחשוב אחרת?</h2><p>מפתחות החישוב נותנים לילדים דרך ברורה לגשת לתרגילים, לפרק אותם ולבחור איך לפתור.</p><a className="cta" href="#join">להצטרפות לקורס <ArrowLeft size={21}/></a></section></main><footer className="footer"><Brand/><nav className="footer-links" aria-label="קישורים בתחתית האתר"><span>יצירת קשר</span><span>תנאי שימוש</span><span>מדיניות פרטיות</span><span>הצהרת נגישות</span><span>מדיניות ביטולים</span></nav><p className="copyright">© 2026 kidodo. כל הזכויות שמורות.</p></footer></div>}
